# Generated by Django 5.2.6 on 2025-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_order_called_at_order_comment_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='комментарий менеджера'),
        ),
    ]
